### ISSUE TITLE
building Error

### ISSUE THREAD

**Issue by TonyStark** [Numenorean/ExpressVPN-Auth#1]
Build Error:=`ExpressVPN-Auth/client.go:50:3: cannot use c.Proxy (type string) as type fasthttp.DialFunc in field value`
Go Version:= `go version go1.16.7 linux/amd64`
OS info:= `Linux arch 5.10.32-1-MANJARO #1 SMP Wed Apr 21 14:54:10 UTC 2021 x86_64 GNU/Linux`

**Comment by TonyStark** [comment]
i tried with frida script, but that also gives error
```-> Error: expected a pointer at <eval> (/ssl.js:7)```

**Comment by Numenorean** [comment]
Fixed. Please get a new version and confirm

**Comment by Numenorean** [comment]
> i tried with frida script, but that also gives error
> `-> Error: expected a pointer at <eval> (/ssl.js:7)`

did you try it on the iphone or another apple's device?

**Comment by TonyStark** [comment]
i dont have iphone, i have tried in genymotion
i think that script only work in ios expressvpn version

new version compiled successfully (:+1: )
